server:
  port: 8080

spring:
  profiles:
    active: mysql-dev
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:192.168.33.200}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngominhquang12a2nl@gmail.com
    password: ybmgcirgufdpzcob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ngominhquang12a2nl@gmail.com
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.socket: DEBUG
jwt:
  expiry-time-secs: 3600
  access-key: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=

minio:
  access:
    key: ${S3_ACCESS_KEY_ID:ysgde2yaW6fO0SWEItUi}
  secret:
    key: ${S3_SECRET_ACCESS_KEY:d5ZUamQKwuY2NOhBktqLm9GCtOzpaAkD1G4mogKW}
  url:
    public: ${S3_ENDPOINT:http://localhost:9000}
    private: ${S3_ENDPOINT_PRIVATE:http://localhost:9000}
  bucket: ${S3_BUCKET:find-job}

