services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-13T20-26-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./docker/s3:/data
    command: server /data --console-address ":9001"
